object BuildVersions {

    const val DYNAMIC_FEATURES = "2.3.0"
    const val KOTLIN = "1.4.0"
    const val KOTLIN_COROUTINES = "1.3.9"
    const val CONSTRAIN_LAYOUT = "2.0.1"
    const val CORE_KTX = "1.3.1"
    const val APPCOMPAT = "1.2.0"
    const val ROOM_DB = "2.2.5"
    const val NAVIGATION = "2.2.0"
    const val NAVIGATION_FRAGMENT = NAVIGATION
    const val RETROFIT = "2.7.0"
    const val HTTP_LOGGING = "4.2.2"
    const val MOSHI = "1.9.2"
    const val TIMBER = "4.7.1"
    const val ANDROIDX_LEGACY = "1.0.0"
    const val PLAY_CORE = "1.8.0"
    const val DATABINDING = "4.0.1"
    const val MATERIAL_COMPONENTS = "1.2.0"
    const val PAGING_KTX = "2.1.2"
    const val DAGGER_HILT = "2.28-alpha"
    const val LIFECYCLE = "2.2.0"
    const val COIL = "0.13.0"
    const val RECYCLE_VIEW = "1.1.0"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val HILT_VIEWMODEL = "1.0.0-alpha01"
    const val DYNAMIC_NAV_HOST = "2.3.0"

    // Tests
    const val JUNIT = "4.13"
    const val JUNIT5 = "5.7.0"
    const val JUNIT_PLATFORM = "1.7.0"
    const val ANDROIDX_JUNIT = "1.1.2"
    const val ESPRESSO = "3.3.0"
    const val NAVIGATION_TESTING = NAVIGATION
    const val TRUTH = "1.0.1"
    const val MOCKITO = "2.19.0"
    const val HAMCREST = "2.2"
    const val ARCH_CORE = "2.1.0"
    const val COROUTINE = "1.3.7"
    const val MOCKITO_ = "2.2.0"
    const val MOCKK = "1.9.3"
    const val ANDROIDX_RUNNER = "1.3.0"
    const val ROBOLECTRIC = "4.3.1"
    const val OBJENESIS = "2.6"
}